### ISSUE TITLE
<circle> attributes do not include "fill"

### ISSUE THREAD

**Issue by yurivish** [wooorm/svg-element-attributes#1]
Hi! I noticed some missing properties when playing around with your dataset here.  😄 

`fill` on `<circle>` is missing:

https://github.com/wooorm/svg-element-attributes/blob/2b028fecbf10df35162e63ee50308138068331a6/index.json#L246

This also seems to be the case for many other elements, such as `<rect>`.  And`stroke` is also missing. Did you mean to leave these out for some reason, or was it an accidental omission?

[Section M.2](https://www.w3.org/TR/SVG/attindex.html) of the SVG 1.1 spec has a list of styling attributes and the elements on which they may be present.

**Comment by wooorm** [comment]
Hey @yurivish! Thanks for contributing! :)

You’re right! Because of the build script, the [presentation attributes](https://www.w3.org/TR/SVG/attindex.html#PresentationAttributes) aren't added (by mistake), as you point out.

I‘m wondering though: adding them to all those elements increases the size a lot! It used to be 2.86 kB (min+gzip) or 17 kB (min), but with this fix would be 3.76 kB (min+gzip) or 62 kB (min).

That’s quite the increase! Maybe we could add another special category? `@` for all the presentational attributes, and potentially `@` in each element that can have them?

Do you have any ideas?

**Comment by yurivish** [comment]
That depends on how this package is used — do you know what people typically use it for? In my case I'm using the data in your excellent packages for validating  HTML/SVG tags and attributes and am preprocessing the JSONs anyway, so the size of the files isn't an issue.

People who care about code size and are shipping the data to the client are almost certainly using gzip, and for people who aren't the size increase is probably not important. 

I was exploring a compression scheme earlier that collected all tag/attribute names into a set and represented each one by an unsigned 16-bit integer index. Tag-attribute pairs can then be represented as 32-bit integers.

I decided to hold off on further work until later, but if you're interested in compressing the size of the raw data then that might be a good way to go. 😄

**Comment by wooorm** [comment]
You’re right! Done :)
