### ISSUE TITLE
<svg> attributes missing xmlns and version

### ISSUE THREAD

**Issue by yurivish** [wooorm/svg-element-attributes#2]
It should be allowed at least on `<svg>` according to https://www.w3.org/TR/SVG/struct.htm

I haven't determined what the most comprehensive fix here would be, but adding these two would be a start. 😄

**Comment by wooorm** [comment]
Hi @yurivish!

The `version` was added in [1.2.1](https://github.com/wooorm/svg-element-attributes/blob/78d2f4a197e2a019601b93157885152c52d1b9a9/index.json#L3708), so it should be in there!

For `xmlns`, and other XML related attributes, they should be in another package I think. They could be used in other XML documents as well (such as HTML or MathML), so I don’t think we should add them here!

**Comment by yurivish** [comment]
Hi @wooorm,

Thanks for the reply, here and on the other thread. Silly mistake on my part there. 😄 

And great, I should update to the latest for `version` — thanks!

For `xmlns`, you're probably right that lots of specific XML attributes should not have to be in a package for SVG element attributes, but I think this one's special: 

> In all cases, for compliance with the Namespaces in XML Recommendation [XML-NS], an SVG namespace declaration must be provided so that all SVG elements are identified as belonging to the SVG namespace. The following are possible ways to provide a namespace declaration. An ‘xmlns’ attribute without a namespace prefix could be specified on an ‘svg’ element, which means that SVG is the default namespace for all elements within the scope of the element with the ‘xmlns’ attribute:
>
> `<svg xmlns="http://www.w3.org/2000/svg" …>`
> `  <rect …/>`
> `</svg>`

This is from the [spec](https://www.w3.org/TR/2011/REC-SVG11-20110816/struct.html), which doesn't seem to allow linking directly to that section.

The other ways of providing namespace declarations all also involve adding an `xmlns` or `xmlns:svg` attribute. 

So I'm not 100% sure, since this is a bit beyond my full understanding, but it seems that if we just add this one (or two, counting `xmlns:svg`), then it enables you to create valid SVG files using the information in your package for validation.

**Comment by wooorm** [comment]
Hi, thanks for waiting, sorry about that!

I Googled a bit, and found [this stack overflow question](https://stackoverflow.com/questions/18467982/are-svg-parameters-such-as-xmlns-and-version-needed). It seems the `xmlns` is indeed required for separate SVG files (served as `image/svg+xml`).

I dunno, I feel like:
- [The description in the readme](https://github.com/wooorm/svg-element-attributes#svg-element-attributes-) specifically mentions that XML attributes are not included in this project
- A separate `xml-element-attributes` (or the like) package may be useful
- Adding `xmlns` here now will just lead to more attributes (`xml:*`, `xlink:*`) later (and `xlink` is actually used a bit in SVG!)
- The stuff needed for smart matches (`xml:*` to allow `xml:lang` etc...) just adds more logic to this package
- This problem may be fixed in your case with a simple if/else statement in your code!

What do you think?

**Comment by wooorm** [comment]
@yurivish Ping!

**Comment by yurivish** [comment]
Hi! One moment... 😄

**Comment by yurivish** [comment]
Thanks for the research and thoughts -- I actually ended up deciding _not_ to validate things to this degree for the [library](https://github.com/yurivish/Hyperscript.jl) that I'm writing (since it turns out that enforcing strictness here is more annoying than useful), so I don't have any strong feelings on the matter any more.

In my case it would have been useful to have "all" the attributes, including from XML, but I can see why you might want to keep them separate since it's easier for the user to combine them than decouple them themselves

**Comment by wooorm** [comment]
Ahh right, well good luck with your project and thanks for filing this issue, but I’m closing this as a wontfix for now!
